auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
exclude: [shower,themes]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: Andrew Grigorev
    url:  https://github.com/ei-grad
    company:
        name: Yandex
        url:  http://www.yandex.ru

fork_url: https://github.com/ei-grad/jekyller
progress: true
